### ISSUE TITLE
wfaCreateTCPServSock has two different definitions

### ISSUE THREAD

**Issue by cbaudele** [Wi-FiTestSuite/Wi-FiTestSuite-Linux-DUT#18]
1. ./inc/wfa_sock.h:extern int wfaCreateTCPServSock(unsigned short sport);

2. ./lib/wfa_sock.c:int wfaCreateTCPServSock(char *devIface, unsigned short port)

Used with (1) here:
./dut/wfa_dut.c:    gagtSockfd = wfaCreateTCPServSock(locPortNo);
./ca/wfa_ca.c:    tmsockfd = wfaCreateTCPServSock(myport);

Used with (2) here:
./lib/wfa_nw_al.c:                    wfaCreateTCPServSock(handle->if_attr.ipConn.device, handle->if_attr.ipConn.port);

**Comment by WFA-kdhara** [comment]
taken care with new upload in develop branch
