### ISSUE TITLE
Missing some headers in integration of SIG-1358

### ISSUE THREAD

**Issue by cbaudele** [Wi-FiTestSuite/Wi-FiTestSuite-Linux-DUT#19]
Following integration of SIG-1358 #resolve, there are some missing files in project:
wfa_nw_al.h
wfa_serial.h

Some defs in added files cannot be retrieved as header files are missing...

**Comment by WFA-kdhara** [comment]
Hi 
Thanks,
During upload, some file did not picked up, Now it should be ok, I have checked in all files,
Thanks 
Kali kinkar

**Comment by WFA-kdhara** [comment]
taken care with new upload
